"""init performance standards

Revision ID: 8ca242fbad48
Revises: d2c76908763c
Create Date: 2025-10-01 21:07:08.263056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ca242fbad48'
down_revision: Union[str, Sequence[str], None] = 'd2c76908763c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ref_performance_standards',
    sa.Column('category_id', sa.UUID(), nullable=False, comment='ID Kategori Aktivitas'),
    sa.Column('name', sa.String(), nullable=False, comment='Nama Standar'),
    sa.Column('description', sa.Text(), nullable=True, comment='Deskripsi Standar'),
    sa.Column('evaluation_method', sa.Enum('MANUAL', 'SYSTEM', name='performancestandardsevaluationmethod'), nullable=False, comment='Metode Penilaian'),
    sa.Column('scoring_rules', sa.JSON(), nullable=True, comment='Aturan Penilaian Sistem (JSON)'),
    sa.Column('evaluation_guide', sa.Text(), nullable=True, comment='Panduan Penilaian PM'),
    sa.Column('weight_percentage', sa.DECIMAL(precision=5, scale=2), nullable=False, comment='Bobot Persentase'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['ref_activity_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ref_performance_standards')
    # ### end Alembic commands ###
